name: Build and Publish llmio Docker Image

# 触发条件：推送到 main 分支，或手动触发
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # 形如 ghcr.io/<owner>/llmio

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # 允许写入 ghcr.io

    steps:
      # 1. 检出源码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 QEMU（如需交叉构建 ARM 镜像）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置 Buildx（Docker BuildKit）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 登录到 GitHub Container Registry
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. 提取元数据（标签、版本号）
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      # 6. 构建并推送多架构镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
